# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simpleMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13simpleMessage.proto\"Q\n\x05Hello\x12\x13\n\x06header\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0btestMessage\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_headerB\x0e\n\x0c_testMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simpleMessage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HELLO']._serialized_start=23
  _globals['_HELLO']._serialized_end=104
# @@protoc_insertion_point(module_scope)
